#include <iostream>
#include <thread>
#include <vector>

void task(int id) {
    std::cout << "Thread " << id << " is working...\n";
}

int main(void) {
    std::vector<std::thread> workers;

    for (int i = 0; i < std::thread::hardware_concurrency(); ++i) {
        workers.emplace_back(task, i);
//         Thread Thread 1 is working...
//         Thread 3 is working...       
//         Thread 2 is working...       
//         Thread 7 is working...       
//         Thread 6 is working...       
//         Thread 5 is working...       
//         Thread 4 is working...       
//         0 is working...
    }

    for (auto& t : workers) t.join();
}
